<?php


$root= dirname(__DIR__).DIRECTORY_SEPARATOR.'restapi'.DIRECTORY_SEPARATOR;

DEFINE('VIEW_PATH',$root.DIRECTORY_SEPARATOR.'view'.DIRECTORY_SEPARATOR);
DEFINE('CONTROLLER_PATH',$root.DIRECTORY_SEPARATOR.'controller'.DIRECTORY_SEPARATOR);
define('CONFIG_PATH',$root.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR);
define('MODEL_PATH',$root.DIRECTORY_SEPARATOR.'models'.DIRECTORY_SEPARATOR);


